# Options
printWidth: 80
singleQuote: true
trailingComma: all
useTabs: true

# Visual Studio Code [settings.json]
# "editor.defaultFormatter": "esbenp.prettier-vscode",
# "editor.formatOnSave": true,
# "prettier.requireConfig": true, // optional
